### PR TITLE
Add automation scripts

### PR DESCRIPTION
**Pull request by rbergen**
This adds scripts (and instructions) for some repetitive tasks related to processing changes to the project/repo.

### CODE REVIEW

**Comment by 640-KB** [comment]
I meant to mention this earlier but you can save a huge amount on the Tiny version by doing the same `/merge:.rdata=.text /merge:.data=.text /align:4` trick.  I got Tiny.exe to 1,640 bytes just by doing that.

**Comment by rbergen** [comment]
Thanks for mentioning this. As Tiny is @davepl's original code, I'll leave it up to him if he wants to do this. As it stands, his "Crinkled" executable is still the smallest anyway.

**Comment by davepl** [comment]
Thanks for doing this!

**Comment by davepl** [comment]
Tiny.exe doesn’t use the linker at all, it’s built using crinkler, and it handles the sections on its own.  It doesn’t allow you to manually merge sections because it’s got its own funky way of doing it, but it seems to work!  I’m at 631 bytes as of now…

 

*	Dave

**Comment by davepl** [comment]
629!  Every byte is sacred, every byte is great, when a byte is wasted, God gets quite irate…

 

From: ***@***.*** ***@***.***> 
Sent: Tuesday, January 10, 2023 11:52 AM
To: 'PlummersSoftwareLLC/HelloAssembly' ***@***.***>; 'PlummersSoftwareLLC/HelloAssembly' ***@***.***>
Cc: 'David W Plummer' ***@***.***>; 'Mention' ***@***.***>
Subject: RE: [PlummersSoftwareLLC/HelloAssembly] Add automation scripts (PR #15)

 

Tiny.exe doesn’t use the linker at all, it’s built using crinkler, and it handles the sections on its own.  It doesn’t allow you to manually merge sections because it’s got its own funky way of doing it, but it seems to work!  I’m at 631 bytes as of now…

 

*	Dave

**Comment by rbergen** [comment]
Hahaha, that actually made me laugh out loud :)

**Comment by davepl** [comment]
616 now, so I’m going for lunch 😊

 

From: ***@***.*** ***@***.***> 
Sent: Tuesday, January 10, 2023 11:55 AM
To: 'PlummersSoftwareLLC/HelloAssembly' ***@***.***>; 'PlummersSoftwareLLC/HelloAssembly' ***@***.***>
Cc: 'David W Plummer' ***@***.***>; 'Mention' ***@***.***>
Subject: RE: [PlummersSoftwareLLC/HelloAssembly] Add automation scripts (PR #15)

 

629!  Every byte is sacred, every byte is great, when a byte is wasted, God gets quite irate…

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: Tuesday, January 10, 2023 11:52 AM
To: 'PlummersSoftwareLLC/HelloAssembly' ***@***.*** ***@***.***> >; 'PlummersSoftwareLLC/HelloAssembly' ***@***.*** ***@***.***> >
Cc: 'David W Plummer' ***@***.*** ***@***.***> >; 'Mention' ***@***.*** ***@***.***> >
Subject: RE: [PlummersSoftwareLLC/HelloAssembly] Add automation scripts (PR #15)

 

Tiny.exe doesn’t use the linker at all, it’s built using crinkler, and it handles the sections on its own.  It doesn’t allow you to manually merge sections because it’s got its own funky way of doing it, but it seems to work!  I’m at 631 bytes as of now…

 

*	Dave

**Comment by 640-KB** [comment]
> Every byte is sacred, every byte is great, when a byte is wasted, God gets quite irate… 

That's the truest thing anyone has ever said on the Internet!

May I quote you on that and include it in a ROM BIOS project I'm working on?

**Comment by davepl** [comment]
You sure can, but I think I stole it from a Monty Python skit I saw as a teenager…  so it’s parody but not original!

 

Lemme check… yup!   Thank goodness for the Internet:

 

https://youtu.be/fUspLVStPbk?t=22

 

(It’s OK, because I’m RC and have lots of kids 😊 )

 

Cheers,

Dave

**Comment by 640-KB** [comment]
> You sure can, but I think I stole it from a Monty Python skit I saw as a teenager… so it’s parody but not original! Lemme check… yup! Thank goodness for the Internet: https://youtu.be/fUspLVStPbk?t=22 (It’s OK, because I’m RC and have lots of kids 😊 ) 

I'm no lawyer, but I'd agree that qualifies as parody. That said -- and I don't want to speak for everyone -- I believe most reasonable people would upon hearing that, immediately identify it as something Dave Plummer had said rather than a bunch of obscure Brits from the 1970's.  That would go a long way in a court of law in your favor.

And finally... I declare my project complete.  Thank you!

https://github.com/640-KB/GLaBIOS/blob/main/src/GLABIOS.ASM#L23

**Pull request merged**
