### PR TITLE
Save 4 bytes with minor asm golfing

### PR DESCRIPTION
**Pull request by 640-KB**
Note: I am not able to fully test this because I do not seem to have a Win32/Win64 compatible version of LINK.EXE.

### CODE REVIEW

**Comment by rbergen** [comment]
I've tested your changes, and they don't seem to make any change to the executable size with either build method (with or without the use of Crinkler). As such, I don't see a reason to merge this.

**Comment by 640-KB** [comment]
That is very strange.  The obj file was 1,142 bytes before and 1,138 bytes after and I can count that those 4 opcode changes were each 1 byte shorter.  Do you see the same sizes of the obj files before and after?

**Comment by rbergen** [comment]
I can confirm the size difference in the obj file. 

You may well be right about what Crinkler is doing. However, what actually surprised me most is that the executable generated without Crinkler also isn't smaller: 1248 bytes with and without your changes. All in all, it seems it's less Crinkler than the linker in general.

Any changes that do decrease the executable size are welcome, of course. There is another PR open (#9) that does indeed take bytes off the executables (both with and without Crinkler). I expect to merge that PR soon, maybe you can take the code after merging as the basis for your future changes.

**Comment by rbergen** [comment]
#9 is now merged.

**Comment by rbergen** [comment]
@640-KB Lasse may have "accidentally" found the reason for the executables not decreasing in size while the obj file does. It's quite likely related to segment alignment, which is indeed a linker affair. Long story short: you could try building the executable without Crinkler using `/align:4` instead of `/align:16` in the `ml` command parameters. If that does lead to a smaller executable with your changes in, I'm happy to proceed with merging your changes if you choose to reopen your PR.

**Comment by 640-KB** [comment]
Interesting. I suspected something like that but just ran out of time to investigate (I didn't want to do another PR without being able to actually test it). Good news is that I did find the compatible LINK.EXE so I can build it that way too.

I'll pull latest changes and resubmit another PR or two with some of the other suggestions I had.
________________________________

**Comment by rbergen** [comment]
Ok, that's obviously perfectly fine!

**Comment by 640-KB** [comment]
Right, simpler to reopen!

**Comment by 640-KB** [comment]
And with `/align:4` using LINK it does indeed lower the EXE by 4 bytes, so seems like it would be worth merging.

My next proposed changes save an additional 24 bytes in the EXE.  I'll submit them as new PRs once this is merged to stay in sync.

**Review by rbergen — APPROVED** [review]
LGTM

**Comment by davepl** [comment]
It might even run on ALIGN:1 because x86 doesn’t have alignment constraints, but there could be other reasons for wide alignment I can’t think of!

**Comment by rbergen** [comment]
What I find interesting is that Crinkler also seems to apply some sort of alignment; the executable produced by it also doesn't decrease in size unless some threshold is reached.

**Comment by 640-KB** [comment]
I think that `.model flat` sets the segment align to 4 and ML won't let you override that in the command line with `/ALIGN:1`.  May we assume going forward that we use align 4 instead of 16?

**Comment by rbergen** [comment]
Yes. I'll soon update the build instructions in the repo README to use `/ALIGN:4`.

**Comment by davepl** [comment]
Sounds good to me!

**Comment by rbergen** [comment]
Cool! Done!

**Comment by 640-KB** [comment]
Is this `push ax` here intentional, or should it be `push eax`?

https://github.com/PlummersSoftwareLLC/HelloAssembly/blob/ddd751d4d85408088eb52599e8cdfe14ac6ed4d0/Lasse/LittleWindows.asm#L286

**Pull request merged**
