### PR TITLE
Fix call to API with wrong character set.

### PR DESCRIPTION
**Pull request by chazste**
DispatchMessageW was being called even though the rest of the program is/was using ANSI APIs. Fix pointer and call.

Signed-off-by: Charles Stevens <chazste@yahoo.com>

### CODE REVIEW

**Comment by rbergen** [comment]
Confirmed the exe still works, updated size table timestamp; the sizes themselves didn't change.

**Comment by rbergen** [comment]
@chazste I forgot to ask you if you're ok with the README update that I pushed to your PR branch. If so, I'm happy to merge.

**Comment by chazste** [comment]
Yup looks good to me. I appreciate you updating the readme!

**Review by rbergen — APPROVED** [review]
LGTM

**Pull request merged**
